apiVersion: v1
kind: Secret
metadata:
    name: test
    namespace: arc-runners
data:
    test: ENC[AES256_GCM,data:NjE6I3x74nQ=,iv:qhFhGFrqtP3mEv7YMUpaiGxmIXiZMFba9S4DADXXGdI=,tag:2Za28zTV6vQCmKOVJrY7VA==,type:str]
sops:
    age:
        - recipient: age13qg6tpdjfjxcucc9v0lprl2q8wfzvstamh6a6zhnmedq835f3ehsc56thu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0LzAzVm5OSnB1dzlqays5
            ck5oaGhaMElPSkNzVm5kTlhSVGtvZS9xd1FvCnIrWStWME0wQm96UW1sTnlBSTZs
            ek5nUC9UUUI5dklqSmF0YU1kMVFVOW8KLS0tIHZSTEhzOTBuQjl0QkpSaFBUYWpj
            THUwbVd0ZC9jYThsTmZHWnhhYWJMWEUKnIJcQoQkhz+ZWdxNSXhMDDF6nQcijsKM
            Ac8jHaTtReVFLqIguivgw9zjaA60LXPEoAs+0YM/l/Wc5HRh0IKW7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f8vgexpv2fs0yhjes9tqn0rum4j7l0lxupxk66nn7jpa6cyh3etsqqd0ee
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMHFzd0ZiY053TW9RR0FS
            anRwT0dhbTUzV1pnVjd1aE11c3VWakVuTkY4Cm5IZCtpWXh6MEVad1Q4WFNuNE4y
            RDhvSCtsakhleExxTXJlMW5aYjJISlkKLS0tIHRnNHE4MXpEUjlWRGdYa3g1eVU3
            emFOREx0YThGekJkRmNXOWpRdEZXTjgK3h9dyFJ39yFjlAP4JUuZKIkMXQA9dwIV
            bs7VRySbNDyGfSVfecD+UsKZNFMa+hL5YmXg8z5H6GHCLU4vyjkmNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T22:11:11Z"
    mac: ENC[AES256_GCM,data:noyzoScL3q9go3juC29/rFkV0I7krmaAfBt8SR48Zr6fK9QPCtmTlX/Zpaw8TI0BcxC98PPS+SLk3VvmdGFO1ABAsD5jBQYMKdW26yZFxaOgyUTLZVNIH+g1udCQ3VdQOCw2EbJ2A6khRILHIeM/jTYe5m+p/cUUPTF14+/HYF4=,iv:zM3gu7Xbs8GzhAuQotF0BzbqcK4409GndhTnDLWETnE=,tag:m7J7qjD9redIyGKJtNUVkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
